apiVersion: v1
kind: Service
metadata:
  name: prispulsen-api
  namespace: prispulsen
  labels:
    app: prispulsen-api
spec:
  type: ClusterIP
  selector:
    app: prispulsen-api
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
