apiVersion: v1
kind: Service
metadata:
  name: prispulsen-frontend
  namespace: prispulsen
  labels:
    app: prispulsen-frontend
spec:
  type: ClusterIP
  selector:
    app: prispulsen-frontend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
